### ISSUE TITLE
Etsy Connection Reset Error

### ISSUE THREAD

**Issue by mahesh352** [etsy/open-api#828]
### Discussed in https://github.com/etsy/open-api/discussions/824

<div type='discussions-op-text'>

<sup>Originally posted by **mahesh352** January 18, 2023</sup>
Hi Team,

We are frequently facing below error while making call to Etsy. It used to work fine and no changes on our side.

URL : [https://openapi.etsy.com:443/v3/application/shops?shop_name=purpleboho2](https://openapi.etsy.com/v3/application/shops?shop_name=purpleboho2) 
 
 
Error:
 
2023-01-12T15:54:14.949-05:00 DEBUG [http-nio2-8080-exec-1] [15] o.a.h.wire:87 - wire - http-outgoing-7967 << "[read] I/O error: Connection reset"
2023-01-12T15:54:14.949-05:00 DEBUG [http-nio2-8080-exec-1] [15] o.a.h.i.c.DefaultManagedHttpClientConnection:79 - close - http-outgoing-7967: Close connection
2023-01-12T15:54:14.949-05:00 DEBUG [http-nio2-8080-exec-1] [15] o.a.h.i.c.DefaultManagedHttpClientConnection:96 - shutdown - http-outgoing-7967: Shutdown connection
2023-01-12T15:54:14.949-05:00 DEBUG [http-nio2-8080-exec-1] [15] o.a.h.i.e.MainClientExec:129 - abortConnection - Connection discarded
2023-01-12T15:54:14.950-05:00 DEBUG [http-nio2-8080-exec-1] [15] o.a.h.i.c.PoolingHttpClientConnectionManager:351 - releaseConnection - Connection released: [id: 7967][route: {s}->https://openapi.etsy.com:443][total/ available: 8; route allocated: 0 of 5; total allocated: 9 of 10]
2023-01-12T15:54:14.950-05:00 INFO  [http-nio2-8080-exec-1] [15] o.a.h.i.e.RetryExec:97 - execute - I/O exception (java.net.SocketException) caught when processing request to {s}->[https://openapi.etsy.com:443](https://openapi.etsy.com/): Connection reset
2023-01-12T15:54:14.950-05:00 DEBUG [http-nio2-8080-exec-1] [15] o.a.h.i.e.RetryExec:104 - execute - Connection reset
java.net.SocketException: Connection reset
               at java.net.SocketInputStream.read(SocketInputStream.java:210) ~[?:1.8.0_181]
               at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[?:1.8.0_181]
               at sun.security.ssl.InputRecord.readFully(InputRecord.java:465) ~[?:1.8.0_181]
               at sun.security.ssl.InputRecord.read(InputRecord.java:503) ~[?:1.8.0_181]
               at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983) ~[?:1.8.0_181]

Attaching complete debug log for your reference (api keys removed), please let me know why this will happen only for few requests and not for all.

[etsy_timeout_error.txt](https://github.com/etsy/open-api/files/10451249/etsy_timeout_error.txt)

Thanks,
Mahesh
</div>

**Comment by emergingdzns** [comment]
We also have run into this error a bunch lately.
```
[ERROR] cURL error 35: OpenSSL SSL_connect: Connection reset by peer in connection to openapi.etsy.com:443  (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://openapi.etsy.com/v3/public/oauth/token
```

Would appreciate any insight you have on what would be causing this lately.
